version: '3.8'

services:
  # Backend Service
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./env.example
    environment:
      - FLASK_ENV=development
      - USE_MOCK_SERVICES=true
      - DATABASE_URL=sqlite:///app.db
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    depends_on:
      - db
      - redis
    networks:
      - secureai-network

  # Frontend Service
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - secureai-network

  # Database Service
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=secureai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - secureai-network

  # Redis Service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - secureai-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - secureai-network

volumes:
  postgres_data:
  redis_data:

networks:
  secureai-network:
    driver: bridge
